############################################
#    Simple Commercial Gamma Camera Head   #
#    Collimator with Hexagonal Holes       #
#    Gate V9.0                             #
#    Stathis STILIARIS, May-2023           #
############################################
#    Jaszczak Phantom with Cold Spot       #
############################################

#
# V I S U A L I S A T I O N
#
# /vis/open OGLI 800x800+000+000
# /vis/viewer/set/viewpointThetaPhi +0 +0
# /vis/viewer/zoom  1.2
# /vis/drawVolume
# /vis/enable
# /vis/viewer/set/style surface
# /vis/viewer/flush
#
# /tracking/verbose         0
# /tracking/storeTrajectory 1
#
# /vis/scene/endOfEventAction accumulate 50
#/vis/scene/endOfRunAction refresh
# /vis/scene/add/trajectories
#/vis/scene/add/hits
# /vis/modeling/trajectories/create/drawByCharge
#/vis/viewer/update
#/vis/reviewKeptEvents
#/vis/viewer/set/autoRefresh true
#/vis/viewer/flush


#
# Material Database
#
/gate/geometry/setMaterialDatabase GateMaterials.db

#
# W O R L D
#
/gate/world/geometry/setXLength  1000 mm
/gate/world/geometry/setYLength  1000 mm
/gate/world/geometry/setZLength   700 mm

#
# A X E S
#
# /vis/scene/add/axes

#
# Detector Volumes
#
/gate/world/daughters/name SPECThead
/gate/world/daughters/insert cylinder
/gate/SPECThead/geometry/setRmin       0 mm
/gate/SPECThead/geometry/setRmax     500 mm
/gate/SPECThead/geometry/setHeight   700 mm
/gate/SPECThead/placement/setTranslation  0  0  0 mm
/gate/SPECThead/setMaterial Air
/gate/SPECThead/vis/setColor white
/gate/SPECThead/vis/forceWireframe

#
# DETECTOR Space (ATTENTION: Max absolute Y-Translation is 400 mm) 
#
/gate/SPECThead/daughters/name Det
/gate/SPECThead/daughters/insert box
/gate/Det/geometry/setXLength        420.0 mm
/gate/Det/geometry/setYLength         50.0 mm
/gate/Det/geometry/setZLength        600.0 mm
/gate/Det/placement/setTranslation     0.0  -200.0   0.0 mm
/gate/Det/setMaterial  Air
/gate/Det/vis/setColor magenta
/gate/Det/vis/forceWireframe

#
# Absorber: NaI DETECTOR
#
/gate/Det/daughters/name Abs
/gate/Det/daughters/insert box
/gate/Abs/geometry/setXLength         400.0 mm
/gate/Abs/geometry/setYLength          10.0 mm
/gate/Abs/geometry/setZLength          50.0 mm
#/gate/Abs/geometry/setZLength         540.0 mm
/gate/Abs/placement/setTranslation      0.0   -18.0   0.0 mm
/gate/Abs/setMaterial  NaI
/gate/Abs/vis/setColor blue
#/gate/Abs/vis/forceSolid
/gate/Abs/vis/forceWireframe

#
# Collimator
#
/gate/Det/daughters/name Coll
/gate/Det/daughters/insert box
/gate/Coll/geometry/setXLength        410.0 mm
/gate/Coll/geometry/setYLength         36.0 mm
/gate/Coll/geometry/setZLength        100.0 mm
#/gate/Coll/geometry/setZLength        550.0 mm
/gate/Coll/placement/setTranslation     0.0    +6.0   0.0 mm
/gate/Coll/setMaterial Lead
/gate/Coll/vis/setColor red
#/gate/Coll/vis/forceSolid
/gate/Coll/vis/forceWireframe

/gate/Coll/daughters/name   hole
/gate/Coll/daughters/insert hexagone
/gate/hole/geometry/setHeight  36.00 mm
/gate/hole/geometry/setRadius   0.60 mm
/gate/hole/placement/setRotationAxis   1 0 0
/gate/hole/placement/setRotationAngle 90 deg
/gate/hole/setMaterial  Air
/gate/hole/vis/setColor white
/gate/hole/vis/forceWireframe

/gate/hole/repeaters/insert cubicArray
/gate/hole/cubicArray/setRepeatNumberX 153
/gate/hole/cubicArray/setRepeatNumberY 1
/gate/hole/cubicArray/setRepeatNumberZ 051
/gate/hole/cubicArray/setRepeatVector  2.600  0.000   1.500 mm
#
/gate/hole/repeaters/insert linear
/gate/hole/linear/setRepeatNumber      2
/gate/hole/linear/setRepeatVector      1.300  0.000   0.750 mm


#
# Repeater
#
/gate/Det/repeaters/insert ring
/gate/Det/ring/setRepeatNumber 2


#
# Rotation
#
/gate/SPECThead/placement/setRotationAxis   0 0 1
/gate/SPECThead/placement/setRotationAngle  {ANG} deg


#
# Phantom
#
/gate/world/daughters/name   Phantom
/gate/world/daughters/insert cylinder
/gate/Phantom/geometry/setRmin         00.0 mm 
/gate/Phantom/geometry/setRmax        100.0 mm
/gate/Phantom/geometry/setHeight       10.0 mm
/gate/Phantom/placement/setTranslation  0.0     0.0   0.0 mm
/gate/Phantom/placement/setRotationAngle   00 deg
/gate/Phantom/setMaterial  Water
/gate/Phantom/vis/setColor grey
/gate/Phantom/vis/forceWireframe

/gate/world/daughters/name   ColdR
/gate/world/daughters/insert cylinder
/gate/ColdR/geometry/setRmin         00.0 mm 
/gate/ColdR/geometry/setRmax         12.5 mm
/gate/ColdR/geometry/setHeight       10.0 mm
/gate/ColdR/placement/setTranslation  -60.0    0.0   0.0 mm
/gate/ColdR/setMaterial  Water
/gate/ColdR/vis/setColor blue
/gate/ColdR/vis/forceWireframe

#
# Lead Phantom to check source activity
#
# /gate/SPECThead/daughters/name   PP
# /gate/SPECThead/daughters/insert cylinder
# /gate/PP/geometry/setRmin          0.0 mm 
# /gate/PP/geometry/setRmax        100.0 mm
# /gate/PP/geometry/setHeight       20.0 mm
# /gate/PP/placement/setTranslation  0.0     0.0   0.0 mm
# /gate/PP/placement/setRotationAngle   00 deg
# /gate/PP/setMaterial  Lead
# /gate/PP/vis/setColor grey
# /gate/PP/vis/forceWireframe

/gate/geometry/rebuild

#
# SAVE Detector SetUp
#
#/vis/ogl/set/printMode vectored
#/vis/ogl/set/exportFormat pdf
#/vis/ogl/printEPS

#-------------------oooooOOOOO00000OOOOOooooo---------------------#
#                                                                 #
#              S E N S I T I V E   D E T E C T O R                #
#                                                                 #
#-------------------oooooOOOOO00000OOOOOooooo---------------------#

# 
# Crystal SD
#
/gate/systems/SPECThead/crystal/attach Det
#/gate/Det/attachCrystalSD
#/gate/Coll/attachCrystalSD
/gate/Abs/attachCrystalSD

#
# Source Activity Measure with Lead PP 
#
# /gate/systems/SPECThead/crystal/attach PP
# /gate/PP/attachCrystalSD

#
# Phantom SD
#
# /gate/P0/attachPhantomSD
# /gate/P1/attachPhantomSD
# /gate/P2/attachPhantomSD
# /gate/Collimator/attachPhantomSD

#-------------------oooooOOOOO00000OOOOOooooo---------------------#
#                                                                 #
#     D E F I N I T I O N   A N D   D E S C R I T I O N           #
#             O F   Y O U R   P H Y S I C S                       #
#                                                                 #
#-------------------oooooOOOOO00000OOOOOooooo---------------------#

# EM  P R O C E S S

/gate/physics/addProcess PhotoElectric
/gate/physics/addProcess Compton gamma
/gate/physics/addProcess RayleighScattering gamma
/gate/physics/addProcess GammaConversion

/gate/physics/processes/PhotoElectric/setModel      StandardModel
/gate/physics/processes/Compton/setModel            StandardModel
/gate/physics/processes/RayleighScattering/setModel LivermoreModel
/gate/physics/processes/GammaConversion/setModel    StandardModel

/gate/physics/addProcess ElectronIonisation e-
/gate/physics/addProcess ElectronIonisation e+

/gate/physics/processes/ElectronIonisation/setModel StandardModel e-
/gate/physics/processes/ElectronIonisation/setModel StandardModel e+

/gate/physics/processList Enabled
/gate/physics/processList Initialized

#
# C U T S
#
/gate/physics/Gamma/SetCutInRegion              world 0.05 mm
/gate/physics/Electron/SetCutInRegion           world 0.01 mm
/gate/physics/Positron/SetCutInRegion           world 0.01 mm

/gate/physics/SetMaxToFInRegion                 world 0.01 s
/gate/physics/SetMinKineticEnergyInRegion       world 2.00 keV

/gate/physics/displayCuts

#-------------------oooooOOOOO00000OOOOOooooo---------------------#
#                                                                 #
#     I N I T I A L I Z A T I O N   O F   Y O U R                 #
#                 S I M U L A T I O N                             #
#                                                                 #
#-------------------oooooOOOOO00000OOOOOooooo---------------------#

/gate/run/initialize

#-------------------oooooOOOOO00000OOOOOooooo---------------------#
#                                                                 #
#  D E F I N I T I O N   O F   Y O U R   A C Q U I S I T I O N    #
#  D I G I T I Z E R   &   C O I N C I D E N C E   S H O R T E R  #
#                                                                 #
#-------------------oooooOOOOO00000OOOOOooooo---------------------#

/gate/output/digi/enable

#
# A D D E R
#
/gate/digitizer/Singles/insert adder

#
# R E A D O U T 
#
# /gate/digitizer/Singles/insert readout
# /gate/digitizer/Singles/readout/setDepth 1

#
# E N E R G Y   B L U R R I N G
#
/gate/digitizer/Singles/insert blurring
/gate/digitizer/Singles/blurring/setResolution 0.075
/gate/digitizer/Singles/blurring/setEnergyOfReference 662. keV

#-------------------oooooOOOOO00000OOOOOooooo---------------------#
#                                                                 #
#                   D E F I N I T I O N   O F                     #
#                Y O U R   O U T P U T   F I L E                  #
#                                                                 #
#-------------------oooooOOOOO00000OOOOOooooo---------------------#

/gate/output/analysis/enable
/gate/output/ascii/enable
/gate/output/root/disable
/gate/output/projection/disable
/gate/output/interfile/disable

#
# C H A N G E    T H E     S E E D (1)  O R   N O T (0)
#
# /gate/output/root/setSaveRndmFlag 1

#
# S E T U P  R O O T - F I L E
#
# /gate/output/root/setFileName test
# /gate/output/root/setRootHitFlag 1
# /gate/output/root/setRootSinglesFlag 1
# /gate/output/root/setRootNtupleFlag 1

#
# S E T U P  A S C I I - F I L E
#
/gate/output/ascii/setFileName {OUT}
# /gate/output/ascii/setOutFileSinglesAdderFlag 0
# /gate/output/ascii/setOutFileSinglesBlurringFlag 0
/gate/output/ascii/setOutFileSinglesFlag 1
/gate/output/ascii/setOutFileHitsFlag 0

#-------------------oooooOOOOO00000OOOOOooooo---------------------#
#                                                                 #
#                   D E F I N I T I O N   O F                     #
#            Y O U R   V E R B O S I T Y   L E V E L              #
#                                                                 #
#-------------------oooooOOOOO00000OOOOOooooo---------------------#

/control/verbose          0
/run/verbose              0
/event/verbose            0
/tracking/verbose         0
/gate/application/verbose 0
/gate/generator/verbose   0
/gate/source/verbose      0

#-------------------oooooOOOOO00000OOOOOooooo---------------------#
#                                                                 #
#                   D E F I N I T I O N   O F                     #
#                    Y O U R   S O U R C E S                      #
#                                                                 #
#-------------------oooooOOOOO00000OOOOOooooo---------------------#

#
# Gamma Source-0
#
/gate/source/addSource              Src0
/gate/source/Src0/gps/particle      gamma
/gate/source/Src0/gps/energy        159.0 keV
/gate/source/Src0/setActivity     4000000 Bq
/gate/source/Src0/gps/pos/type      Volume
/gate/source/Src0/gps/pos/shape     Cylinder
/gate/source/Src0/gps/pos/radius     100.0 mm
/gate/source/Src0/gps/pos/halfz        5.0 mm
/gate/source/Src0/gps/pos/centre    0.0   0.0  0.0 mm
/gate/source/Src0/gps/ang/type      iso
/gate/source/Src0/gps/ang/mintheta    0.0 deg
/gate/source/Src0/gps/ang/maxtheta  180.0 deg
/gate/source/Src0/gps/ang/minphi      0.0 deg
/gate/source/Src0/gps/ang/maxphi    360.0 deg
#/gate/source/Src0/visualize 100 red 2

#
# Cold Source
#
/gate/source/Src0/gps/Forbid ColdR_phys

#
# Gamma Source-1
#
/gate/source/addSource              Src1
/gate/source/Src1/gps/particle      gamma
/gate/source/Src1/gps/energy        159.0 keV
/gate/source/Src1/setActivity       10000 Bq
/gate/source/Src1/gps/pos/type      Volume
/gate/source/Src1/gps/pos/shape     Cylinder
/gate/source/Src1/gps/pos/radius      2.5 mm
/gate/source/Src1/gps/pos/halfz       5.0 mm
/gate/source/Src1/gps/pos/centre  +60.0    0.0  0.0 mm
/gate/source/Src1/gps/ang/type      iso
/gate/source/Src1/gps/ang/mintheta    0.0 deg
/gate/source/Src1/gps/ang/maxtheta  180.0 deg
/gate/source/Src1/gps/ang/minphi      0.0 deg
/gate/source/Src1/gps/ang/maxphi    360.0 deg
#/gate/source/Src1/visualize 100 red 2

#
# Gamma Source-2
#
/gate/source/addSource              Src2
/gate/source/Src2/gps/particle      gamma
/gate/source/Src2/gps/energy        159.0 keV
/gate/source/Src2/setActivity       40000 Bq
/gate/source/Src2/gps/pos/type      Volume
/gate/source/Src2/gps/pos/shape     Cylinder
/gate/source/Src2/gps/pos/radius      5.0 mm
/gate/source/Src2/gps/pos/halfz       5.0 mm
/gate/source/Src2/gps/pos/centre  +42.4  +42.4  0.0 mm
/gate/source/Src2/gps/ang/type      iso
/gate/source/Src2/gps/ang/mintheta    0.0 deg
/gate/source/Src2/gps/ang/maxtheta  180.0 deg
/gate/source/Src2/gps/ang/minphi      0.0 deg
/gate/source/Src2/gps/ang/maxphi    360.0 deg
#/gate/source/Src2/visualize 100 red 2

#
# Gamma Source-3
#
/gate/source/addSource              Src3
/gate/source/Src3/gps/particle      gamma
/gate/source/Src3/gps/energy        159.0 keV
/gate/source/Src3/setActivity       90000 Bq
/gate/source/Src3/gps/pos/type      Volume
/gate/source/Src3/gps/pos/shape     Cylinder
/gate/source/Src3/gps/pos/radius      7.5 mm
/gate/source/Src3/gps/pos/halfz       5.0 mm 
/gate/source/Src3/gps/pos/centre    0.0  +60.0  0.0 mm
/gate/source/Src3/gps/ang/type      iso
/gate/source/Src3/gps/ang/mintheta    0.0 deg
/gate/source/Src3/gps/ang/maxtheta  180.0 deg
/gate/source/Src3/gps/ang/minphi      0.0 deg
/gate/source/Src3/gps/ang/maxphi    360.0 deg
#/gate/source/Src3/visualize 100 red 2

#
# Gamma Source-4
#
/gate/source/addSource              Src4
/gate/source/Src4/gps/particle      gamma
/gate/source/Src4/gps/energy        159.0 keV
/gate/source/Src4/setActivity      160000 Bq
/gate/source/Src4/gps/pos/type      Volume
/gate/source/Src4/gps/pos/shape     Cylinder
/gate/source/Src4/gps/pos/radius     10.0 mm
/gate/source/Src4/gps/pos/halfz       5.0 mm 
/gate/source/Src4/gps/pos/centre  -42.4  +42.4  0.0 mm
/gate/source/Src4/gps/ang/type      iso
/gate/source/Src4/gps/ang/mintheta    0.0 deg
/gate/source/Src4/gps/ang/maxtheta  180.0 deg
/gate/source/Src4/gps/ang/minphi      0.0 deg
/gate/source/Src4/gps/ang/maxphi    360.0 deg
#/gate/source/Src4/visualize 100 red 2

#
# Gamma Source-5
#
# /gate/source/addSource              Src5
# /gate/source/Src5/gps/particle      gamma
# /gate/source/Src5/gps/energy        159.0 keV
# /gate/source/Src5/setActivity      250000 Bq
# /gate/source/Src5/gps/pos/type      Volume
# /gate/source/Src5/gps/pos/shape     Cylinder
# /gate/source/Src5/gps/pos/radius     12.5 mm
# /gate/source/Src5/gps/pos/halfz       5.0 mm 
# /gate/source/Src5/gps/pos/centre  -60.0    0.0  0.0 mm
# /gate/source/Src5/gps/ang/type      iso
# /gate/source/Src5/gps/ang/mintheta    0.0 deg
# /gate/source/Src5/gps/ang/maxtheta  180.0 deg
# /gate/source/Src5/gps/ang/minphi      0.0 deg
# /gate/source/Src5/gps/ang/maxphi    360.0 deg
# /gate/source/Src5/visualize 100 red 2

#
# Gamma Source-6
#
/gate/source/addSource              Src6
/gate/source/Src6/gps/particle      gamma
/gate/source/Src6/gps/energy        159.0 keV
/gate/source/Src6/setActivity      360000 Bq
/gate/source/Src6/gps/pos/type      Volume
/gate/source/Src6/gps/pos/shape     Cylinder
/gate/source/Src6/gps/pos/radius     15.0 mm
/gate/source/Src6/gps/pos/halfz       5.0 mm 
/gate/source/Src6/gps/pos/centre  -42.4  -42.4  0.0 mm
/gate/source/Src6/gps/ang/type      iso
/gate/source/Src6/gps/ang/mintheta    0.0 deg
/gate/source/Src6/gps/ang/maxtheta  180.0 deg
/gate/source/Src6/gps/ang/minphi      0.0 deg
/gate/source/Src6/gps/ang/maxphi    360.0 deg
#/gate/source/Src6/visualize 100 red 2

#
# Gamma Source-7
#
/gate/source/addSource              Src7
/gate/source/Src7/gps/particle      gamma
/gate/source/Src7/gps/energy        159.0 keV
/gate/source/Src7/setActivity      490000 Bq
/gate/source/Src7/gps/pos/type      Volume
/gate/source/Src7/gps/pos/shape     Cylinder
/gate/source/Src7/gps/pos/radius     17.5 mm
/gate/source/Src7/gps/pos/halfz       5.0 mm 
/gate/source/Src7/gps/pos/centre    0.0  -60.0  0.0 mm
/gate/source/Src7/gps/ang/type      iso
/gate/source/Src7/gps/ang/mintheta    0.0 deg
/gate/source/Src7/gps/ang/maxtheta  180.0 deg
/gate/source/Src7/gps/ang/minphi      0.0 deg
/gate/source/Src7/gps/ang/maxphi    360.0 deg
#/gate/source/Src7/visualize 100 red 2

#
# Gamma Source-8
#
/gate/source/addSource              Src8
/gate/source/Src8/gps/particle      gamma
/gate/source/Src8/gps/energy        159.0 keV
/gate/source/Src8/setActivity      640000 Bq
/gate/source/Src8/gps/pos/type      Volume
/gate/source/Src8/gps/pos/shape     Cylinder
/gate/source/Src8/gps/pos/radius     20.0 mm
/gate/source/Src8/gps/pos/halfz       5.0 mm 
/gate/source/Src8/gps/pos/centre  +42.4  -42.4  0.0 mm
/gate/source/Src8/gps/ang/type      iso
/gate/source/Src8/gps/ang/mintheta    0.0 deg
/gate/source/Src8/gps/ang/maxtheta  180.0 deg
/gate/source/Src8/gps/ang/minphi      0.0 deg
/gate/source/Src8/gps/ang/maxphi    360.0 deg
#/gate/source/Src8/visualize 100 red 2

/gate/source/list

#-------------------oooooOOOOO00000OOOOOooooo---------------------#
#                                                                 #
#               S T A R T   A C Q U I S I T I O N                 #
#                 T I M E   P A R A M E T E R S                   #
#                                                                 #
#-------------------oooooOOOOO00000OOOOOooooo---------------------#

#
# E X P E R I M E N T
#

#/random/setSavingFlag  0
#/random/resetEngineFrom start1.rndm
#/random/setSeeds 1234 5678

/gate/random/setEngineName Ranlux64
/gate/random/setEngineSeed {SEED}

/gate/application/setTimeSlice       5.00  s
/gate/application/setTimeStart       0.00  s
/gate/application/setTimeStop      480.00  s

/gate/application/startDAQ

# /vis/ogl/export   test.pdf

exit

